### ISSUE TITLE
applications for dynamic image denoising

### ISSUE THREAD

**Issue by liyang323** [koflera/LearningRegularizationParameterMaps#2]
Why can't I find the script for 2D dynamic image denoising?

**Comment by liyang323** [comment]
Your reply has been very helpful to me as a newbie in deep learning. I found an error in 'train_dyn_img.py' line 64 that data_mode="real" is not defined. You mentioned in Appendix A.3 that 'the CNN $u_{Theta}$ was constructed as described in section A.1 but with only one output channel per output dimension'. Please check again the related network structure in this part. The following are the changes in my debug:                                                                                                                                                                                                         1. line 38 in download_mot_data.py, 'shutil.move(os.path.join(subset_path, folder_name), os.path.join(destination, folder_name))', add 'subset' between 'destination' and 'folder_name'
2. line  61 in download_mot_data.py, change to 'parser.add_argument("--path", default='../../data/dyn_img', help="output path")'
3. lines 25 and 41, replace 'test' with 'train'

**Comment by schote** [comment]
> Your reply has been very helpful to me as a newbie in deep learning. I found an error in 'train_dyn_img.py' line 64 that data_mode="real" is not defined. You mentioned in Appendix A.3 that 'the CNN $u_{Theta}$ was constructed as described in section A.1 but with only one output channel per output dimension'. Please check again the related network structure in this part. The following are the changes in my debug:                                                                                                                                                                                                         1. line 38 in download_mot_data.py, 'shutil.move(os.path.join(subset_path, folder_name), os.path.join(destination, folder_name))', add 'subset' between 'destination' and 'folder_name'
> 
> 2. line  61 in download_mot_data.py, change to 'parser.add_argument("--path", default='../../data/dyn_img', help="output path")'
> 
> 3. lines 25 and 41, replace 'test' with 'train'

Thank you very much for the feedback @liyang323. Please note that the PR is a draft and still work in progress, the code is not yet fully functional. However, I will complete the PR asap.

**Comment by liyang323** [comment]
👍👍👍
